from fastapi import APIRouter

from app.api.v1 import (
    admin_activation_wave_items,
    admin_activation_waves,
    admin_analytics,
    admin_cockpit,
    admin_local_events,
    admin_neighborhoods,
    admin_organizations,
    admin_partner_creator_contents,
    admin_partner_offers,
    admin_partners,
    admin_platform_config,
    admin_passports,
    admin_reports,
    admin_staff,
    admin_tribes,
    auth,
    comments,
    cultural_places,
    discussions,
    events,
    feed,
    health,
    map,
    neighborhoods,
    notifications,
    organizations,
    partner_leads,
    partner_offers_public,
    partners,
    passport,
    posts,
    profile,
    rbac_validation,
    scan,
    search,
    stories,
    subscriptions,
    transit,
    tribe_invitations,
    tribes,
    users,
    weather,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(profile.router)
api_router.include_router(organizations.router)
api_router.include_router(partner_leads.router)
api_router.include_router(partners.router)
api_router.include_router(partner_offers_public.router)
api_router.include_router(admin_partner_offers.router)
api_router.include_router(admin_cockpit.router)
api_router.include_router(admin_analytics.router)
api_router.include_router(admin_activation_waves.router)
api_router.include_router(admin_activation_wave_items.router)
api_router.include_router(admin_organizations.router)
api_router.include_router(admin_passports.router)
api_router.include_router(admin_partners.router)
api_router.include_router(admin_platform_config.router)
api_router.include_router(admin_partner_creator_contents.router)
api_router.include_router(admin_reports.router)
api_router.include_router(admin_staff.router)
api_router.include_router(admin_local_events.router)
api_router.include_router(admin_neighborhoods.router)
api_router.include_router(events.router)
api_router.include_router(neighborhoods.router)
api_router.include_router(tribes.router)
api_router.include_router(tribe_invitations.router)
api_router.include_router(admin_tribes.router)
api_router.include_router(passport.router)
api_router.include_router(notifications.router)
api_router.include_router(users.router)
api_router.include_router(feed.router)
api_router.include_router(discussions.router)
api_router.include_router(stories.router)
api_router.include_router(posts.router)
api_router.include_router(comments.router)
api_router.include_router(scan.router)
api_router.include_router(search.router)
api_router.include_router(map.router)
api_router.include_router(cultural_places.router)
api_router.include_router(transit.router)
api_router.include_router(subscriptions.router)
api_router.include_router(weather.router)
api_router.include_router(rbac_validation.router)
