"""Public creator hub constants (FEATURE-CREATORS-V1 C1-01)."""

from __future__ import annotations

CREATOR_HUB_LIST_LIMIT_DEFAULT = 24
CREATOR_HUB_LIST_LIMIT_MAX = 50
CREATOR_HUB_RELATED_LIMIT = 3
CREATOR_PROFILE_CONTENTS_LIMIT_DEFAULT = 24
CREATOR_PROFILE_CONTENTS_LIMIT_MAX = 50
CREATOR_DIRECTORY_LIST_LIMIT_DEFAULT = 24
CREATOR_DIRECTORY_LIST_LIMIT_MAX = 50
CREATOR_DIRECTORY_SEARCH_MAX_LENGTH = 128

CREATOR_CONTENT_TYPE_ARTICLE = "article"
CREATOR_CONTENT_TYPE_PHOTO = "photo"

CREATOR_AUTHOR_KIND_PARTNER = "partner"
