"""Cultural places catalog constants (WEB-MAP-03)."""

from __future__ import annotations

CULTURAL_PLACE_LIST_LIMIT_DEFAULT = 8
CULTURAL_PLACE_LIST_LIMIT_MAX = 100
CULTURAL_PLACE_PORTAL_PAGE_SIZE_DEFAULT = 12
CULTURAL_PLACE_SORT_FEATURED = "featured"
CULTURAL_PLACE_SORT_NAME = "name"
CULTURAL_PLACE_SORT_RECENT = "recent"
CULTURAL_PLACE_MAP_LIMIT_DEFAULT = 50
CULTURAL_PLACE_MAP_LIMIT_MAX = 100
