"""Event map API constants (FEATURE-D / TICKET-D.3)."""

from __future__ import annotations

MAP_EVENTS_LIMIT_DEFAULT = 100
MAP_EVENTS_LIMIT_MAX = 100
MAP_BBOX_MAX_SURFACE_DEG2 = 0.25
MAP_RATE_LIMIT = 30
MAP_RATE_WINDOW_SECONDS = 60
MAP_DESCRIPTION_MAX_LENGTH = 120
