"""Neighborhood catalog constants (TICKET-602 / PRD-601)."""

from enum import StrEnum

NEIGHBORHOOD_CITY_MAX_LENGTH = 128
NEIGHBORHOOD_SLUG_MAX_LENGTH = 80
NEIGHBORHOOD_DISPLAY_NAME_MAX_LENGTH = 120
NEIGHBORHOOD_SHORT_DESCRIPTION_MAX_LENGTH = 2000
NEIGHBORHOOD_AMBIANCE_MAX_LENGTH = 32
NEIGHBORHOOD_COVER_URL_MAX_LENGTH = 500
NEIGHBORHOOD_ACCENT_COLOR_MAX_LENGTH = 16

NEIGHBORHOOD_LIST_PAGE_SIZE_DEFAULT = 20
NEIGHBORHOOD_LIST_PAGE_SIZE_MAX = 50

NEIGHBORHOOD_CONTEXT_EVENTS_LIMIT = 10
NEIGHBORHOOD_CONTEXT_ORGS_LIMIT = 12
NEIGHBORHOOD_CONTEXT_OFFERS_LIMIT = 10
NEIGHBORHOOD_CONTEXT_POSTS_LIMIT = 10


class NeighborhoodAmbiance(StrEnum):
    """Editorial ambiance — not exposed as competitive labels."""

    CALM = "calm"
    LIVELY = "lively"
    CULTURAL = "cultural"
    STUDENT = "student"
    GREEN = "green"


MVP_NEIGHBORHOOD_AMBIANCES: frozenset[str] = frozenset(a.value for a in NeighborhoodAmbiance)
