"""Pilot territory goals and thresholds (ADMIN-SETTINGS-01B)."""

from __future__ import annotations

PILOT_STATUS_ACTIVE = "active"

PASSPORT_OPS_PILOT_GOAL = 50
OFFERS_CATALOG_PILOT_GOAL = 10
EVENTS_AGENDA_PILOT_GOAL = 10
CREATOR_CONTENT_EDITORIAL_PILOT_GOAL = 10
PARTNER_LEAD_PILOT_QUALIFIED_GOAL = 25

MODERATION_ATTENTION_THRESHOLD = 5
STAFF_CRITICAL_ROLE_COUNT = 3
